version: '3'
name: path-planner
services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432
